/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encripptador;

/**
 *
 * @author Albert Jose Charry, Jorge Andres Duran
 * @version 1.1 02 de Marzo de 2017
 */
public class interfac extends javax.swing.JFrame {

    /**
     * Creates new form interfac
     */
    public interfac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sal1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        fin = new javax.swing.JLabel();
        equ = new javax.swing.JLabel();
        letr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("separar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(sal1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equ, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(284, 284, 284)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(ingre, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letr, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ingre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sal1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equ, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(letr, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String cadena = ingre.getText();

int arreglo_final[] =  new int[255];

int dimension = cadena.length();

int numerot = Integer.parseInt(num.getText());



int cont1 = 0;
String separadas = "";
int valor_letra = 0;

String todasequ = "";
while(cont1 < dimension){

    char letra = cadena.charAt(cont1);
    separadas = separadas + letra+"-";

    
  int  equiva = transforma(letra);
  todasequ = todasequ + equiva + " - ";
    System.out.println(""+equiva);
    
int result = (numerot - equiva)%27;

if(result < 0){

result = result * -1;

}
    
  arreglo_final[cont1] = result;
    
cont1 = cont1 + 1;
}

equ.setText(todasequ);

int cont2 = 0;
int limit2 = arreglo_final.length;
String impri = "";
String impri2 = "";
while(cont2 < limit2){

impri = impri +arreglo_final[cont2] +" - ";

    int numero_1 = arreglo_final[cont2];

    
impri2 = impri2 + mostrarle(numero_1) + " - ";
 if(arreglo_final[cont2] == 0){
cont2 = limit2;
    
}

cont2 = cont2 + 1;
}

fin.setText(impri);
letr.setText(impri2);
sal1.setText(separadas);

    
    }//GEN-LAST:event_jButton1ActionPerformed

    public char mostrarle(int a){
    char b = '0';
    
    if(a == 1){
    
        b = 'a';
    
    }
 if(a == 2){
    
    b = 'b';
     
    }
  if(a == 3){
    
    b = 'c';
     
    }
     if(a == 4){
    
    b = 'd';
     
    }
       
     if(a == 5){
    
    b = 'e';
     
    }
     if(a == 6){
    
    b = 'f';
     
    }
     if(a == 7){
    
    b = 'g';
     
    }
    
     if(a == 8){
    
    b = 'h';
     
    }
     if(a == 9){
    
    b = 'i';
     
    }
     if(a == 10){
    
    b = 'j';
     
    }
     if(a == 11){
    
    b = 'k';
     
    }
     if(a == 12){
    
    b = 'l';
     
    }
     if(a == 13){
    
    b = 'm';
     
    }
     if(a == 14){
    
    b = 'n';
     
    }
     if(a == 15){
    
    b = 'ñ';
     
    }
     if(a == 16){
    
    b = 'o';
     
    }
     if(a == 17){
    
    b = 'p';
     
    }
     if(a == 18){
    
    b = 'q';
     
    }
     if(a == 19){
    
    b = 'r';
     
    }
     if(a == 20){
    
    b = 's';
     
    }
     if(a == 21){
    
    b = 't';
     
    }
     if(a == 22){
    
    b = 'u';
     
    }
     if(a == 23){
    
    b = 'v';
     
    }
     if(a == 24){
    
    b = 'w';
     
    }
     if(a == 25){
    
    b = 'x';
     
    }
     if(a == 26){
    
    b = 'y';
     
    }
     if(a == 27){
    
    b = 'z';
     
    }
     if(a == 28){
    
    b = '*';
     
    }
    
    return b;
    }
    
public int transforma(char letra){

    int valor_letra = 0;
    
if(letra == 'a' || letra == 'A'){

    valor_letra = 1;

}
if(letra == 'b' || letra == 'B'){

    valor_letra = 2;

}
if(letra == 'c' || letra == 'C'){

    valor_letra = 3;

}
if(letra == 'd' || letra == 'D'){

    valor_letra = 4;

}
if(letra == 'e' || letra == 'E'){

    valor_letra = 5;

}
if(letra == 'f' || letra == 'F'){

    valor_letra = 6;

}
if(letra == 'g' || letra == 'G'){

    valor_letra = 7;

}
if(letra == 'h' || letra == 'H'){

    valor_letra = 8;

}
if(letra == 'i' || letra == 'I'){

    valor_letra = 9;

}
if(letra == 'j' || letra == 'J'){

    valor_letra = 10;

}
if(letra == 'k' || letra == 'K'){

    valor_letra = 11;

}
if(letra == 'l' || letra == 'L'){

    valor_letra = 12;

}
if(letra == 'm' || letra == 'M'){

    valor_letra = 13;

}
if(letra == 'n' || letra == 'N'){

    valor_letra = 14;

}
if(letra == 'ñ' || letra == 'Ñ'){

    valor_letra = 15;

}
if(letra == 'o' || letra == 'O'){

    valor_letra = 16;

}
if(letra == 'p' || letra == 'P'){

    valor_letra = 17;

}
if(letra == 'q' || letra == 'Q'){

    valor_letra = 18;

}
if(letra == 'r' || letra == 'R'){

    valor_letra = 19;

}
if(letra == 's' || letra == 'S'){

    valor_letra = 20;

}
if(letra == 't' || letra == 'T'){

    valor_letra = 21;

}
if(letra == 'u' || letra == 'U'){

    valor_letra = 21;

}
if(letra == 'v' || letra == 'V'){

    valor_letra = 22;

}
if(letra == 'w' || letra == 'W'){

    valor_letra = 23;

}
if(letra == 'x' || letra == 'X'){

    valor_letra = 24;

}
if(letra == 'y' || letra == 'Y'){

    valor_letra = 25;

}
if(letra == 'z' || letra == 'Z'){

    valor_letra = 26;

}
if(letra == ' '){

    valor_letra = 27;

}


return valor_letra;
}    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equ;
    private javax.swing.JLabel fin;
    private javax.swing.JTextField ingre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel letr;
    private javax.swing.JTextField num;
    private javax.swing.JLabel sal1;
    // End of variables declaration//GEN-END:variables
}
